// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acl_actor_role.sql

package db

import (
	"context"
)

const addRoleToActor = `-- name: AddRoleToActor :exec
INSERT INTO acl_actor_role (actor_id, facility, role, grantor_cid, granted_at)
VALUES (?, ?, ?, ?, ?)
`

type AddRoleToActorParams struct {
	ActorID    int32
	Facility   string
	Role       string
	GrantorCid int32
	GrantedAt  int64
}

func (q *Queries) AddRoleToActor(ctx context.Context, arg AddRoleToActorParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToActor,
		arg.ActorID,
		arg.Facility,
		arg.Role,
		arg.GrantorCid,
		arg.GrantedAt,
	)
	return err
}

const getRolesForActor = `-- name: GetRolesForActor :many
SELECT id, actor_id, facility, role, grantor_cid, granted_at
FROM acl_actor_role
WHERE actor_id = ?
`

func (q *Queries) GetRolesForActor(ctx context.Context, actorID int32) ([]AclActorRole, error) {
	rows, err := q.db.QueryContext(ctx, getRolesForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AclActorRole
	for rows.Next() {
		var i AclActorRole
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Facility,
			&i.Role,
			&i.GrantorCid,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromActor = `-- name: RemoveRoleFromActor :exec
DELETE
FROM acl_actor_role
WHERE actor_id = ?
  AND facility = ?
  AND role = ?
`

type RemoveRoleFromActorParams struct {
	ActorID  int32
	Facility string
	Role     string
}

func (q *Queries) RemoveRoleFromActor(ctx context.Context, arg RemoveRoleFromActorParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromActor, arg.ActorID, arg.Facility, arg.Role)
	return err
}
