// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acl_user_role.sql

package db

import (
	"context"
)

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO acl_user_role (cid, facility, role, grantor_cid, granted_at)
VALUES (?, ?, ?, ?, ?)
`

type AddRoleToUserParams struct {
	Cid        int32
	Facility   string
	Role       string
	GrantorCid int32
	GrantedAt  int64
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, addRoleToUser,
		arg.Cid,
		arg.Facility,
		arg.Role,
		arg.GrantorCid,
		arg.GrantedAt,
	)
	return err
}

const getRolesForUser = `-- name: GetRolesForUser :many
SELECT id, cid, facility, role, grantor_cid, granted_at
FROM acl_user_role
WHERE cid = ?
`

func (q *Queries) GetRolesForUser(ctx context.Context, cid int32) ([]AclUserRole, error) {
	rows, err := q.db.QueryContext(ctx, getRolesForUser, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AclUserRole
	for rows.Next() {
		var i AclUserRole
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Facility,
			&i.Role,
			&i.GrantorCid,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE
FROM acl_user_role
WHERE cid = ?
  AND facility = ?
  AND role = ?
`

type RemoveRoleFromUserParams struct {
	Cid      int32
	Facility string
	Role     string
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.Cid, arg.Facility, arg.Role)
	return err
}
