// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_log.sql

package db

import (
	"context"
)

const createActionLog = `-- name: CreateActionLog :exec
INSERT INTO action_log (actor_cid, target_cid, action, log, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActionLogParams struct {
	ActorCid  int32
	TargetCid int32
	Action    string
	Log       string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) error {
	_, err := q.db.ExecContext(ctx, createActionLog,
		arg.ActorCid,
		arg.TargetCid,
		arg.Action,
		arg.Log,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getActionLogsForTarget = `-- name: GetActionLogsForTarget :many
SELECT id, actor_cid, target_cid, action, log, created_at, updated_at FROM action_log WHERE target_cid = ? ORDER BY created_at DESC
`

func (q *Queries) GetActionLogsForTarget(ctx context.Context, targetCid int32) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, getActionLogsForTarget, targetCid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionLog
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorCid,
			&i.TargetCid,
			&i.Action,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
