// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actor.sql

package db

import (
	"context"
	"database/sql"
)

const getACLGrantsForActor = `-- name: GetACLGrantsForActor :many
SELECT id, actor_id, acl, scope_facility, created_at, created_by_cid
FROM actor_acl
WHERE actor_id = ?
`

func (q *Queries) GetACLGrantsForActor(ctx context.Context, actorID int32) ([]ActorAcl, error) {
	rows, err := q.db.QueryContext(ctx, getACLGrantsForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorAcl
	for rows.Next() {
		var i ActorAcl
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Acl,
			&i.ScopeFacility,
			&i.CreatedAt,
			&i.CreatedByCid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveActorTokens = `-- name: GetActiveActorTokens :many
SELECT
    actor.id,
    actor.name,
    actor.actor_type,
    actor.rate_limit_override,
    actor.rate_limit_bypass,
    actor_token.comment,
    actor_token.token
FROM actor_token
    JOIN actor ON actor_token.actor_id = actor.id
WHERE actor.is_active AND actor_token.is_active
`

type GetActiveActorTokensRow struct {
	ID                int32
	Name              string
	ActorType         string
	RateLimitOverride int32
	RateLimitBypass   bool
	Comment           sql.NullString
	Token             string
}

func (q *Queries) GetActiveActorTokens(ctx context.Context) ([]GetActiveActorTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveActorTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveActorTokensRow
	for rows.Next() {
		var i GetActiveActorTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ActorType,
			&i.RateLimitOverride,
			&i.RateLimitBypass,
			&i.Comment,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
