// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package db

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO event
(title, body, banner_image_url, facility, start_time, end_time, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Title          string
	Body           string
	BannerImageUrl string
	Facility       string
	StartTime      int64
	EndTime        int64
	CreatedAt      int64
	CreatedBy      int32
	UpdatedAt      int64
	UpdatedBy      int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.Title,
		arg.Body,
		arg.BannerImageUrl,
		arg.Facility,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE
FROM event
WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEventById = `-- name: GetEventById :one
SELECT id, title, body, banner_image_url, facility, start_time, end_time, created_at, created_by, updated_at, updated_by
FROM event
WHERE id = ?
`

func (q *Queries) GetEventById(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.BannerImageUrl,
		&i.Facility,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUpcomingEvents = `-- name: GetUpcomingEvents :many
SELECT id, title, body, banner_image_url, facility, start_time, end_time, created_at, created_by, updated_at, updated_by
FROM event
WHERE start_time > ?
ORDER BY start_time DESC
LIMIT ?, ?
`

type GetUpcomingEventsParams struct {
	StartTime int64
	Offset    int32
	Limit     int32
}

func (q *Queries) GetUpcomingEvents(ctx context.Context, arg GetUpcomingEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingEvents, arg.StartTime, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.BannerImageUrl,
			&i.Facility,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE event
SET title            = ?,
    body             = ?,
    banner_image_url = ?,
    facility         = ?,
    start_time       = ?,
    end_time         = ?,
    updated_at       = ?,
    updated_by       =?
WHERE id = ?
`

type UpdateEventParams struct {
	Title          string
	Body           string
	BannerImageUrl string
	Facility       string
	StartTime      int64
	EndTime        int64
	UpdatedAt      int64
	UpdatedBy      int32
	ID             int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.Title,
		arg.Body,
		arg.BannerImageUrl,
		arg.Facility,
		arg.StartTime,
		arg.EndTime,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
