// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facility_title.sql

package db

import (
	"context"
	"database/sql"
)

const assignUserTitle = `-- name: AssignUserTitle :exec
INSERT IGNORE INTO user_title (cid, title_id, grantor_cid, granted_at)
VALUES (?, ?, ?, ?)
`

type AssignUserTitleParams struct {
	Cid        int32
	TitleID    int64
	GrantorCid int32
	GrantedAt  int64
}

func (q *Queries) AssignUserTitle(ctx context.Context, arg AssignUserTitleParams) error {
	_, err := q.db.ExecContext(ctx, assignUserTitle,
		arg.Cid,
		arg.TitleID,
		arg.GrantorCid,
		arg.GrantedAt,
	)
	return err
}

const countUserTitlesByTitleId = `-- name: CountUserTitlesByTitleId :one
SELECT count(*)
FROM user_title
WHERE title_id = ?
`

func (q *Queries) CountUserTitlesByTitleId(ctx context.Context, titleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserTitlesByTitleId, titleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFacilityTitle = `-- name: CreateFacilityTitle :execresult
INSERT INTO facility_title (facility, title, code, created_at)
VALUES (?, ?, ?, ?)
`

type CreateFacilityTitleParams struct {
	Facility  string
	Title     string
	Code      string
	CreatedAt int64
}

func (q *Queries) CreateFacilityTitle(ctx context.Context, arg CreateFacilityTitleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFacilityTitle,
		arg.Facility,
		arg.Title,
		arg.Code,
		arg.CreatedAt,
	)
}

const deleteFacilityTitleById = `-- name: DeleteFacilityTitleById :exec
DELETE FROM facility_title
WHERE id = ?
`

func (q *Queries) DeleteFacilityTitleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFacilityTitleById, id)
	return err
}

const deleteUserTitle = `-- name: DeleteUserTitle :exec
DELETE FROM user_title
WHERE cid = ? AND title_id = ?
`

type DeleteUserTitleParams struct {
	Cid     int32
	TitleID int64
}

func (q *Queries) DeleteUserTitle(ctx context.Context, arg DeleteUserTitleParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserTitle, arg.Cid, arg.TitleID)
	return err
}

const getFacilityTitleById = `-- name: GetFacilityTitleById :one
SELECT id, facility, title, code, created_at FROM facility_title
WHERE id = ?
`

func (q *Queries) GetFacilityTitleById(ctx context.Context, id int64) (FacilityTitle, error) {
	row := q.db.QueryRowContext(ctx, getFacilityTitleById, id)
	var i FacilityTitle
	err := row.Scan(
		&i.ID,
		&i.Facility,
		&i.Title,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const getFacilityTitles = `-- name: GetFacilityTitles :many
SELECT id, facility, title, code, created_at FROM facility_title
WHERE facility = ?
ORDER BY id ASC
`

func (q *Queries) GetFacilityTitles(ctx context.Context, facility string) ([]FacilityTitle, error) {
	rows, err := q.db.QueryContext(ctx, getFacilityTitles, facility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilityTitle
	for rows.Next() {
		var i FacilityTitle
		if err := rows.Scan(
			&i.ID,
			&i.Facility,
			&i.Title,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTitlesByFacility = `-- name: GetUserTitlesByFacility :many
SELECT ft.id, ft.facility, ft.title, ft.code, ut.grantor_cid, ut.granted_at
FROM facility_title ft
JOIN user_title ut ON ut.title_id = ft.id
WHERE ut.cid = ? AND ft.facility = ?
ORDER BY ft.id ASC
`

type GetUserTitlesByFacilityParams struct {
	Cid      int32
	Facility string
}

type GetUserTitlesByFacilityRow struct {
	ID         int64
	Facility   string
	Title      string
	Code       string
	GrantorCid int32
	GrantedAt  int64
}

func (q *Queries) GetUserTitlesByFacility(ctx context.Context, arg GetUserTitlesByFacilityParams) ([]GetUserTitlesByFacilityRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTitlesByFacility, arg.Cid, arg.Facility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTitlesByFacilityRow
	for rows.Next() {
		var i GetUserTitlesByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Facility,
			&i.Title,
			&i.Code,
			&i.GrantorCid,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
