// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facility.sql

package db

import (
	"context"
)

const getFacility = `-- name: GetFacility :one
SELECT id, name, url FROM facility WHERE id = ?
`

func (q *Queries) GetFacility(ctx context.Context, id string) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacility, id)
	var i Facility
	err := row.Scan(&i.ID, &i.Name, &i.Url)
	return i, err
}
