// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: faq_category.sql

package db

import (
	"context"
	"database/sql"
)

const createFaqCategory = `-- name: CreateFaqCategory :execresult
INSERT INTO faq_category (title, sort_order) VALUES (?, ?)
`

type CreateFaqCategoryParams struct {
	Title     string
	SortOrder int32
}

func (q *Queries) CreateFaqCategory(ctx context.Context, arg CreateFaqCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFaqCategory, arg.Title, arg.SortOrder)
}

const deleteFaqCategory = `-- name: DeleteFaqCategory :exec
DELETE FROM faq_category WHERE id = ?
`

func (q *Queries) DeleteFaqCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFaqCategory, id)
	return err
}

const getFaqCategories = `-- name: GetFaqCategories :many
SELECT id, title, sort_order FROM faq_category ORDER BY sort_order, id
`

func (q *Queries) GetFaqCategories(ctx context.Context) ([]FaqCategory, error) {
	rows, err := q.db.QueryContext(ctx, getFaqCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaqCategory
	for rows.Next() {
		var i FaqCategory
		if err := rows.Scan(&i.ID, &i.Title, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaqCategoryById = `-- name: GetFaqCategoryById :one
SELECT id, title, sort_order FROM faq_category WHERE id = ?
`

func (q *Queries) GetFaqCategoryById(ctx context.Context, id int32) (FaqCategory, error) {
	row := q.db.QueryRowContext(ctx, getFaqCategoryById, id)
	var i FaqCategory
	err := row.Scan(&i.ID, &i.Title, &i.SortOrder)
	return i, err
}

const updateFaqCategory = `-- name: UpdateFaqCategory :exec
UPDATE faq_category
SET title = ?, sort_order = ?
WHERE id = ?
`

type UpdateFaqCategoryParams struct {
	Title     string
	SortOrder int32
	ID        int32
}

func (q *Queries) UpdateFaqCategory(ctx context.Context, arg UpdateFaqCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateFaqCategory, arg.Title, arg.SortOrder, arg.ID)
	return err
}
