// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: faq_item.sql

package db

import (
	"context"
	"database/sql"
)

const createFaqItem = `-- name: CreateFaqItem :execresult
INSERT INTO faq_item (faq_category_id, question, answer, sort_order) VALUES (?, ?, ?, ?)
`

type CreateFaqItemParams struct {
	FaqCategoryID int32
	Question      string
	Answer        string
	SortOrder     int32
}

func (q *Queries) CreateFaqItem(ctx context.Context, arg CreateFaqItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFaqItem,
		arg.FaqCategoryID,
		arg.Question,
		arg.Answer,
		arg.SortOrder,
	)
}

const deleteFaqItem = `-- name: DeleteFaqItem :exec
DELETE FROM faq_item WHERE id = ?
`

func (q *Queries) DeleteFaqItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFaqItem, id)
	return err
}

const getAllFaqItems = `-- name: GetAllFaqItems :many
SELECT id, faq_category_id, question, answer, sort_order FROM faq_item ORDER BY faq_category_id, sort_order, id
`

func (q *Queries) GetAllFaqItems(ctx context.Context) ([]FaqItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllFaqItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaqItem
	for rows.Next() {
		var i FaqItem
		if err := rows.Scan(
			&i.ID,
			&i.FaqCategoryID,
			&i.Question,
			&i.Answer,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaqItemById = `-- name: GetFaqItemById :one
SELECT id, faq_category_id, question, answer, sort_order FROM faq_item WHERE id = ?
`

func (q *Queries) GetFaqItemById(ctx context.Context, id int32) (FaqItem, error) {
	row := q.db.QueryRowContext(ctx, getFaqItemById, id)
	var i FaqItem
	err := row.Scan(
		&i.ID,
		&i.FaqCategoryID,
		&i.Question,
		&i.Answer,
		&i.SortOrder,
	)
	return i, err
}

const updateFaqItem = `-- name: UpdateFaqItem :exec
UPDATE faq_item
SET faq_category_id = ?, question = ?, answer = ?, sort_order = ?
WHERE id = ?
`

type UpdateFaqItemParams struct {
	FaqCategoryID int32
	Question      string
	Answer        string
	SortOrder     int32
	ID            int32
}

func (q *Queries) UpdateFaqItem(ctx context.Context, arg UpdateFaqItemParams) error {
	_, err := q.db.ExecContext(ctx, updateFaqItem,
		arg.FaqCategoryID,
		arg.Question,
		arg.Answer,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
