// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy_controllers_patch.sql

package db

import (
	"context"
)

const provisionLegacyController = `-- name: ProvisionLegacyController :exec

INSERT IGNORE INTO ` + "`" + `vatusa-old` + "`" + `.controllers
    (cid, fname, lname, email, facility, rating, created_at, updated_at,
     facility_join, flag_homecontroller, lastactivity, prefname)
VALUES
    (?, ?, ?, ?, ?, ?, NOW(), NOW(), NOW(), ?, NOW(), 0)
`

type ProvisionLegacyControllerParams struct {
	Cid                uint32
	Fname              string
	Lname              string
	Email              string
	Facility           string
	Rating             int32
	FlagHomecontroller int32
}

// LEGACY-CONTROLLERS-PATCH: temporary support for `current` (legacy Laravel site), which
// still authenticates via `vatusa-old.controllers`. Delete this file and its Go caller
// (grep LEGACY-CONTROLLERS-PATCH) once `current` no longer depends on that table.
func (q *Queries) ProvisionLegacyController(ctx context.Context, arg ProvisionLegacyControllerParams) error {
	_, err := q.db.ExecContext(ctx, provisionLegacyController,
		arg.Cid,
		arg.Fname,
		arg.Lname,
		arg.Email,
		arg.Facility,
		arg.Rating,
		arg.FlagHomecontroller,
	)
	return err
}
