// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate_policies.sql

package db

import (
	"context"
	"database/sql"
)

const getLegacyPolicies = `-- name: GetLegacyPolicies :many
SELECT id, ident, category, title, slug, description, extension, effective_date, perms, visible, ` + "`" + `order` + "`" + `
FROM ` + "`" + `vatusa-old` + "`" + `.policies
ORDER BY category, ` + "`" + `order` + "`" + `, id
`

type GetLegacyPoliciesRow struct {
	ID            uint32
	Ident         string
	Category      uint32
	Title         string
	Slug          string
	Description   string
	Extension     string
	EffectiveDate sql.NullTime
	Perms         string
	Visible       bool
	Order         uint16
}

func (q *Queries) GetLegacyPolicies(ctx context.Context) ([]GetLegacyPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyPoliciesRow
	for rows.Next() {
		var i GetLegacyPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Ident,
			&i.Category,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Extension,
			&i.EffectiveDate,
			&i.Perms,
			&i.Visible,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyPolicyCategories = `-- name: GetLegacyPolicyCategories :many
SELECT id, name, ` + "`" + `order` + "`" + `
FROM ` + "`" + `vatusa-old` + "`" + `.policy_categories
ORDER BY ` + "`" + `order` + "`" + `, id
`

type GetLegacyPolicyCategoriesRow struct {
	ID    uint32
	Name  string
	Order uint16
}

func (q *Queries) GetLegacyPolicyCategories(ctx context.Context) ([]GetLegacyPolicyCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyPolicyCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyPolicyCategoriesRow
	for rows.Next() {
		var i GetLegacyPolicyCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Order); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyCategoryByTitle = `-- name: GetPolicyCategoryByTitle :one
SELECT id, title, sort_order FROM policy_category WHERE title = ?
`

func (q *Queries) GetPolicyCategoryByTitle(ctx context.Context, title string) (PolicyCategory, error) {
	row := q.db.QueryRowContext(ctx, getPolicyCategoryByTitle, title)
	var i PolicyCategory
	err := row.Scan(&i.ID, &i.Title, &i.SortOrder)
	return i, err
}

const getPolicyDocumentByIdent = `-- name: GetPolicyDocumentByIdent :one
SELECT id, policy_category_id, ident, title, summary, document_url, effective_date, hidden, sort_order, created_by_cid, updated_by_cid, created_at, updated_at FROM policy_document WHERE ident = ?
`

func (q *Queries) GetPolicyDocumentByIdent(ctx context.Context, ident string) (PolicyDocument, error) {
	row := q.db.QueryRowContext(ctx, getPolicyDocumentByIdent, ident)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.PolicyCategoryID,
		&i.Ident,
		&i.Title,
		&i.Summary,
		&i.DocumentUrl,
		&i.EffectiveDate,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedByCid,
		&i.UpdatedByCid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
