// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate_action_log.sql

package db

import (
	"context"
)

const getLegacyActionLogs = `-- name: GetLegacyActionLogs :many
SELECT id, ` + "`" + `from` + "`" + `, ` + "`" + `to` + "`" + `, log, created_at, updated_at
FROM ` + "`" + `vatusa-old` + "`" + `.action_log
`

func (q *Queries) GetLegacyActionLogs(ctx context.Context) ([]VatusaOldActionLog, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyActionLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VatusaOldActionLog
	for rows.Next() {
		var i VatusaOldActionLog
		if err := rows.Scan(
			&i.ID,
			&i.From,
			&i.To,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
