// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate_user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getLegacyControllerByCID = `-- name: GetLegacyControllerByCID :one
SELECT c.cid, c.facility, c.rating, c.discord_id
FROM ` + "`" + `vatusa-old` + "`" + `.controllers c
where c.cid = ?
`

type GetLegacyControllerByCIDRow struct {
	Cid       uint32
	Facility  string
	Rating    int32
	DiscordID sql.NullString
}

func (q *Queries) GetLegacyControllerByCID(ctx context.Context, cid uint32) (GetLegacyControllerByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLegacyControllerByCID, cid)
	var i GetLegacyControllerByCIDRow
	err := row.Scan(
		&i.Cid,
		&i.Facility,
		&i.Rating,
		&i.DiscordID,
	)
	return i, err
}

const getLegacyControllerRatingFromPromotionsToMigrate = `-- name: GetLegacyControllerRatingFromPromotionsToMigrate :many
SELECT p.cid, cast(max(` + "`" + `to` + "`" + `) as signed) as max_rating
FROM ` + "`" + `vatusa-old` + "`" + `.promotions p
         JOIN ` + "`" + `vatusa-old` + "`" + `.controllers c ON p.cid = c.cid
where ` + "`" + `to` + "`" + ` <= 7
  and c.rating > 5
group by p.cid
`

type GetLegacyControllerRatingFromPromotionsToMigrateRow struct {
	Cid       int32
	MaxRating int64
}

func (q *Queries) GetLegacyControllerRatingFromPromotionsToMigrate(ctx context.Context) ([]GetLegacyControllerRatingFromPromotionsToMigrateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyControllerRatingFromPromotionsToMigrate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyControllerRatingFromPromotionsToMigrateRow
	for rows.Next() {
		var i GetLegacyControllerRatingFromPromotionsToMigrateRow
		if err := rows.Scan(&i.Cid, &i.MaxRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyControllersToMigrate = `-- name: GetLegacyControllersToMigrate :many
SELECT c.cid, c.facility, c.rating, c.discord_id, TRIM(CONCAT_WS(' ', c.fname, c.lname)) as display_name
from ` + "`" + `vatusa-old` + "`" + `.controllers c
where c.rating > 0
  AND (
    c.rating > 1 OR c.facility NOT IN ('ZAE', 'ZZN', 'ZZI')
    )
`

type GetLegacyControllersToMigrateRow struct {
	Cid         uint32
	Facility    string
	Rating      int32
	DiscordID   sql.NullString
	DisplayName string
}

func (q *Queries) GetLegacyControllersToMigrate(ctx context.Context) ([]GetLegacyControllersToMigrateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyControllersToMigrate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyControllersToMigrateRow
	for rows.Next() {
		var i GetLegacyControllersToMigrateRow
		if err := rows.Scan(
			&i.Cid,
			&i.Facility,
			&i.Rating,
			&i.DiscordID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyInstructorTA = `-- name: GetLegacyInstructorTA :many
SELECT r.cid, r.role
FROM ` + "`" + `vatusa-old` + "`" + `.roles r
JOIN ` + "`" + `vatusa-old` + "`" + `.controllers c on r.cid = c.cid
where r.role = 'TA' or r.role = 'INS'
group by r.cid, r.role
`

type GetLegacyInstructorTARow struct {
	Cid  uint32
	Role string
}

func (q *Queries) GetLegacyInstructorTA(ctx context.Context) ([]GetLegacyInstructorTARow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyInstructorTA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyInstructorTARow
	for rows.Next() {
		var i GetLegacyInstructorTARow
		if err := rows.Scan(&i.Cid, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyLastCompetencyDateByCID = `-- name: GetLegacyLastCompetencyDateByCID :one
SELECT cid, cast(max(competency_date) as datetime) as last_competency_date
from ` + "`" + `vatusa-old` + "`" + `.controller_eligibility_cache
where competency_date is not null and cid = ?
group by cid
`

type GetLegacyLastCompetencyDateByCIDRow struct {
	Cid                int32
	LastCompetencyDate time.Time
}

func (q *Queries) GetLegacyLastCompetencyDateByCID(ctx context.Context, cid int32) (GetLegacyLastCompetencyDateByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLegacyLastCompetencyDateByCID, cid)
	var i GetLegacyLastCompetencyDateByCIDRow
	err := row.Scan(&i.Cid, &i.LastCompetencyDate)
	return i, err
}

const getLegacyLastCompetencyDateToMigrate = `-- name: GetLegacyLastCompetencyDateToMigrate :many
SELECT cid, cast(max(competency_date) as datetime) as last_competency_date
from ` + "`" + `vatusa-old` + "`" + `.controller_eligibility_cache
where competency_date is not null
group by cid
`

type GetLegacyLastCompetencyDateToMigrateRow struct {
	Cid                int32
	LastCompetencyDate time.Time
}

func (q *Queries) GetLegacyLastCompetencyDateToMigrate(ctx context.Context) ([]GetLegacyLastCompetencyDateToMigrateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyLastCompetencyDateToMigrate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyLastCompetencyDateToMigrateRow
	for rows.Next() {
		var i GetLegacyLastCompetencyDateToMigrateRow
		if err := rows.Scan(&i.Cid, &i.LastCompetencyDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyLastPromotionDateByCID = `-- name: GetLegacyLastPromotionDateByCID :one
SELECT cid, cast(max(created_at) as datetime) as last_promotion_date
from ` + "`" + `vatusa-old` + "`" + `.promotions
where cid = ?
  and ` + "`" + `to` + "`" + ` <= 5
  and ` + "`" + `from` + "`" + ` < 5
group by cid
`

type GetLegacyLastPromotionDateByCIDRow struct {
	Cid               int32
	LastPromotionDate time.Time
}

func (q *Queries) GetLegacyLastPromotionDateByCID(ctx context.Context, cid int32) (GetLegacyLastPromotionDateByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLegacyLastPromotionDateByCID, cid)
	var i GetLegacyLastPromotionDateByCIDRow
	err := row.Scan(&i.Cid, &i.LastPromotionDate)
	return i, err
}

const getLegacyLastPromotionDatesToMigrate = `-- name: GetLegacyLastPromotionDatesToMigrate :many
SELECT cid, cast(max(created_at) as datetime) as last_promotion_date
from ` + "`" + `vatusa-old` + "`" + `.promotions
where ` + "`" + `to` + "`" + ` <= 5
  and ` + "`" + `from` + "`" + ` < 5
group by cid
`

type GetLegacyLastPromotionDatesToMigrateRow struct {
	Cid               int32
	LastPromotionDate time.Time
}

func (q *Queries) GetLegacyLastPromotionDatesToMigrate(ctx context.Context) ([]GetLegacyLastPromotionDatesToMigrateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyLastPromotionDatesToMigrate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyLastPromotionDatesToMigrateRow
	for rows.Next() {
		var i GetLegacyLastPromotionDatesToMigrateRow
		if err := rows.Scan(&i.Cid, &i.LastPromotionDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyLastTransferDateByCID = `-- name: GetLegacyLastTransferDateByCID :one
SELECT cid, cast(max(created_at) as datetime) as last_transfer_date
from ` + "`" + `vatusa-old` + "`" + `.transfers
WHERE cid = ?
  and status = 1
group by cid
`

type GetLegacyLastTransferDateByCIDRow struct {
	Cid              uint32
	LastTransferDate time.Time
}

func (q *Queries) GetLegacyLastTransferDateByCID(ctx context.Context, cid uint32) (GetLegacyLastTransferDateByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLegacyLastTransferDateByCID, cid)
	var i GetLegacyLastTransferDateByCIDRow
	err := row.Scan(&i.Cid, &i.LastTransferDate)
	return i, err
}

const getLegacyLastTransferDateToMigrate = `-- name: GetLegacyLastTransferDateToMigrate :many
SELECT cid, cast(max(created_at) as datetime) as last_transfer_date
from ` + "`" + `vatusa-old` + "`" + `.transfers
WHERE status = 1
group by cid
`

type GetLegacyLastTransferDateToMigrateRow struct {
	Cid              uint32
	LastTransferDate time.Time
}

func (q *Queries) GetLegacyLastTransferDateToMigrate(ctx context.Context) ([]GetLegacyLastTransferDateToMigrateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyLastTransferDateToMigrate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyLastTransferDateToMigrateRow
	for rows.Next() {
		var i GetLegacyLastTransferDateToMigrateRow
		if err := rows.Scan(&i.Cid, &i.LastTransferDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyRoleAssignments = `-- name: GetLegacyRoleAssignments :many
SELECT r.cid, r.facility, r.role, r.created_at
FROM ` + "`" + `vatusa-old` + "`" + `.roles r
`

type GetLegacyRoleAssignmentsRow struct {
	Cid       uint32
	Facility  string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) GetLegacyRoleAssignments(ctx context.Context) ([]GetLegacyRoleAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyRoleAssignmentsRow
	for rows.Next() {
		var i GetLegacyRoleAssignmentsRow
		if err := rows.Scan(
			&i.Cid,
			&i.Facility,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegacyRoles = `-- name: GetLegacyRoles :many
SELECT r.cid, r.role, r.facility
FROM ` + "`" + `vatusa-old` + "`" + `.roles r
`

type GetLegacyRolesRow struct {
	Cid      uint32
	Role     string
	Facility string
}

func (q *Queries) GetLegacyRoles(ctx context.Context) ([]GetLegacyRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyRolesRow
	for rows.Next() {
		var i GetLegacyRolesRow
		if err := rows.Scan(&i.Cid, &i.Role, &i.Facility); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
