// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Actor struct {
	ID                int32
	Name              string
	ActorType         string
	FacilityOwner     sql.NullString
	CidOwner          sql.NullInt32
	RateLimitOverride int32
	RateLimitBypass   bool
	IsActive          bool
	CreatedAt         int64
	CreatedByCid      int32
}

type ActorAcl struct {
	ID            int64
	ActorID       int32
	Acl           string
	ScopeFacility string
	CreatedAt     int64
	CreatedByCid  int32
}

type ActorToken struct {
	ID           int32
	ActorID      int32
	Comment      sql.NullString
	Token        string
	IsActive     bool
	CreatedAt    int64
	CreatedByCid int32
	UpdatedAt    int64
	UpdatedByCid int32
}

type NewsPost struct {
	ID        int32
	Title     string
	Body      string
	AuthorCid int32
	PostTime  int64
}

type RoleFacility struct {
	ID        int64
	Cid       int32
	Role      string
	Facility  string
	CreatedAt int64
	CreatedBy int32
}

type RoleGlobal struct {
	ID        int64
	Cid       int32
	Role      string
	CreatedAt int64
	CreatedBy int32
}
