// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AclActorRole struct {
	ID         int64
	ActorID    int32
	Facility   string
	Role       string
	GrantorCid int32
	GrantedAt  int64
}

type AclUserRole struct {
	ID         int64
	Cid        int32
	Facility   string
	Role       string
	GrantorCid int32
	GrantedAt  int64
}

type Actor struct {
	ID                int32
	Name              string
	ActorType         string
	FacilityOwner     sql.NullString
	CidOwner          sql.NullInt32
	RateLimitOverride int32
	RateLimitBypass   bool
	IsActive          bool
	CreatedAt         int64
	CreatedByCid      int32
}

type ActorToken struct {
	ID           int32
	ActorID      int32
	Comment      sql.NullString
	Token        string
	IsActive     bool
	CreatedAt    int64
	CreatedByCid int32
	UpdatedAt    int64
	UpdatedByCid int32
}

type Event struct {
	ID             int64
	Title          string
	Body           string
	BannerImageUrl string
	Facility       string
	StartTime      int64
	EndTime        int64
	CreatedAt      int64
	CreatedBy      int32
	UpdatedAt      int64
	UpdatedBy      int32
}

type NewsPost struct {
	ID        int32
	Title     string
	Body      string
	AuthorCid int32
	PostTime  int64
	EditTime  int64
}

type VatsimUser struct {
	Cid                int64
	NameFirst          string
	NameLast           string
	Email              string
	Rating             int32
	Pilotrating        int32
	Militaryrating     int32
	SuspendDate        sql.NullTime
	RegistrationDate   sql.NullTime
	RegionID           string
	DivisionID         string
	SubdivisionID      sql.NullString
	LatestRatingChange sql.NullTime
	LastSync           time.Time
}
