// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news_post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO news_post (title, body, author_cid, post_time) VALUES (?, ?, ?, ?)
`

type CreatePostParams struct {
	Title     string
	Body      string
	AuthorCid int32
	PostTime  int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Body,
		arg.AuthorCid,
		arg.PostTime,
	)
	return err
}

const deleteNewsPostById = `-- name: DeleteNewsPostById :exec
DELETE FROM news_post WHERE id = ?
`

func (q *Queries) DeleteNewsPostById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteNewsPostById, id)
	return err
}

const getPostById = `-- name: GetPostById :one
SELECT id, title, body, author_cid, post_time FROM news_post WHERE id = ?
`

func (q *Queries) GetPostById(ctx context.Context, id int32) (NewsPost, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.AuthorCid,
		&i.PostTime,
	)
	return i, err
}

const getRecentNewsPosts = `-- name: GetRecentNewsPosts :many
SELECT id, title, body, author_cid, post_time FROM news_post order by id desc limit ?
`

func (q *Queries) GetRecentNewsPosts(ctx context.Context, limit int32) ([]NewsPost, error) {
	rows, err := q.db.QueryContext(ctx, getRecentNewsPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsPost
	for rows.Next() {
		var i NewsPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorCid,
			&i.PostTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
