// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news_post.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO news_post (title, body, author_cid, post_time) VALUES (?, ?, ?, ?)
`

type CreatePostParams struct {
	Title     string
	Body      string
	AuthorCid int32
	PostTime  int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Body,
		arg.AuthorCid,
		arg.PostTime,
	)
}

const deleteNewsPostById = `-- name: DeleteNewsPostById :exec
DELETE FROM news_post WHERE id = ?
`

func (q *Queries) DeleteNewsPostById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteNewsPostById, id)
	return err
}

const getNewsPostsPage = `-- name: GetNewsPostsPage :many
SELECT id, title, body, author_cid, post_time, edit_time
FROM news_post
ORDER BY id DESC
LIMIT ?, ?
`

type GetNewsPostsPageParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetNewsPostsPage(ctx context.Context, arg GetNewsPostsPageParams) ([]NewsPost, error) {
	rows, err := q.db.QueryContext(ctx, getNewsPostsPage, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsPost
	for rows.Next() {
		var i NewsPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorCid,
			&i.PostTime,
			&i.EditTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT id, title, body, author_cid, post_time, edit_time FROM news_post WHERE id = ?
`

func (q *Queries) GetPostById(ctx context.Context, id int32) (NewsPost, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.AuthorCid,
		&i.PostTime,
		&i.EditTime,
	)
	return i, err
}

const getRecentNewsPosts = `-- name: GetRecentNewsPosts :many
SELECT id, title, body, author_cid, post_time, edit_time FROM news_post order by id desc limit ?
`

func (q *Queries) GetRecentNewsPosts(ctx context.Context, limit int32) ([]NewsPost, error) {
	rows, err := q.db.QueryContext(ctx, getRecentNewsPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsPost
	for rows.Next() {
		var i NewsPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorCid,
			&i.PostTime,
			&i.EditTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE news_post
SET title = ?, body = ?, edit_time = ?
WHERE id = ?
`

type UpdatePostParams struct {
	Title    string
	Body     string
	EditTime int64
	ID       int32
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Body,
		arg.EditTime,
		arg.ID,
	)
	return err
}
