// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_document.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPolicyDocument = `-- name: CreatePolicyDocument :execresult
INSERT INTO policy_document (policy_category_id, ident, title, summary, document_url, effective_date, hidden, sort_order, created_by_cid, updated_by_cid, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePolicyDocumentParams struct {
	PolicyCategoryID int32
	Ident            string
	Title            string
	Summary          string
	DocumentUrl      string
	EffectiveDate    time.Time
	Hidden           bool
	SortOrder        int32
	CreatedByCid     int32
	UpdatedByCid     int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreatePolicyDocument(ctx context.Context, arg CreatePolicyDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPolicyDocument,
		arg.PolicyCategoryID,
		arg.Ident,
		arg.Title,
		arg.Summary,
		arg.DocumentUrl,
		arg.EffectiveDate,
		arg.Hidden,
		arg.SortOrder,
		arg.CreatedByCid,
		arg.UpdatedByCid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deletePolicyDocument = `-- name: DeletePolicyDocument :execresult
DELETE FROM policy_document WHERE id = ?
`

func (q *Queries) DeletePolicyDocument(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePolicyDocument, id)
}

const getAllPolicyDocuments = `-- name: GetAllPolicyDocuments :many
SELECT id, policy_category_id, ident, title, summary, document_url, effective_date, hidden, sort_order, created_by_cid, updated_by_cid, created_at, updated_at FROM policy_document ORDER BY policy_category_id, sort_order, id
`

func (q *Queries) GetAllPolicyDocuments(ctx context.Context) ([]PolicyDocument, error) {
	rows, err := q.db.QueryContext(ctx, getAllPolicyDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyDocument
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.PolicyCategoryID,
			&i.Ident,
			&i.Title,
			&i.Summary,
			&i.DocumentUrl,
			&i.EffectiveDate,
			&i.Hidden,
			&i.SortOrder,
			&i.CreatedByCid,
			&i.UpdatedByCid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyDocumentById = `-- name: GetPolicyDocumentById :one
SELECT id, policy_category_id, ident, title, summary, document_url, effective_date, hidden, sort_order, created_by_cid, updated_by_cid, created_at, updated_at FROM policy_document WHERE id = ?
`

func (q *Queries) GetPolicyDocumentById(ctx context.Context, id int32) (PolicyDocument, error) {
	row := q.db.QueryRowContext(ctx, getPolicyDocumentById, id)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.PolicyCategoryID,
		&i.Ident,
		&i.Title,
		&i.Summary,
		&i.DocumentUrl,
		&i.EffectiveDate,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedByCid,
		&i.UpdatedByCid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisiblePolicyDocuments = `-- name: GetVisiblePolicyDocuments :many
SELECT id, policy_category_id, ident, title, summary, document_url, effective_date, hidden, sort_order, created_by_cid, updated_by_cid, created_at, updated_at FROM policy_document WHERE hidden = false ORDER BY policy_category_id, sort_order, id
`

func (q *Queries) GetVisiblePolicyDocuments(ctx context.Context) ([]PolicyDocument, error) {
	rows, err := q.db.QueryContext(ctx, getVisiblePolicyDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyDocument
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.PolicyCategoryID,
			&i.Ident,
			&i.Title,
			&i.Summary,
			&i.DocumentUrl,
			&i.EffectiveDate,
			&i.Hidden,
			&i.SortOrder,
			&i.CreatedByCid,
			&i.UpdatedByCid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyDocument = `-- name: UpdatePolicyDocument :execresult
UPDATE policy_document
SET policy_category_id = ?, ident = ?, title = ?, summary = ?, document_url = ?, effective_date = ?, hidden = ?, sort_order = ?, updated_by_cid = ?, updated_at = ?
WHERE id = ?
`

type UpdatePolicyDocumentParams struct {
	PolicyCategoryID int32
	Ident            string
	Title            string
	Summary          string
	DocumentUrl      string
	EffectiveDate    time.Time
	Hidden           bool
	SortOrder        int32
	UpdatedByCid     int32
	UpdatedAt        time.Time
	ID               int32
}

func (q *Queries) UpdatePolicyDocument(ctx context.Context, arg UpdatePolicyDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePolicyDocument,
		arg.PolicyCategoryID,
		arg.Ident,
		arg.Title,
		arg.Summary,
		arg.DocumentUrl,
		arg.EffectiveDate,
		arg.Hidden,
		arg.SortOrder,
		arg.UpdatedByCid,
		arg.UpdatedAt,
		arg.ID,
	)
}
