// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_category.sql

package db

import (
	"context"
	"database/sql"
)

const countPolicyDocumentsInCategory = `-- name: CountPolicyDocumentsInCategory :one
SELECT COUNT(*) FROM policy_document WHERE policy_category_id = ?
`

func (q *Queries) CountPolicyDocumentsInCategory(ctx context.Context, policyCategoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPolicyDocumentsInCategory, policyCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicyCategory = `-- name: CreatePolicyCategory :execresult
INSERT INTO policy_category (title, sort_order) VALUES (?, ?)
`

type CreatePolicyCategoryParams struct {
	Title     string
	SortOrder int32
}

func (q *Queries) CreatePolicyCategory(ctx context.Context, arg CreatePolicyCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPolicyCategory, arg.Title, arg.SortOrder)
}

const deletePolicyCategory = `-- name: DeletePolicyCategory :execresult
DELETE FROM policy_category WHERE id = ?
`

func (q *Queries) DeletePolicyCategory(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePolicyCategory, id)
}

const getPolicyCategories = `-- name: GetPolicyCategories :many
SELECT id, title, sort_order FROM policy_category ORDER BY sort_order, id
`

func (q *Queries) GetPolicyCategories(ctx context.Context) ([]PolicyCategory, error) {
	rows, err := q.db.QueryContext(ctx, getPolicyCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyCategory
	for rows.Next() {
		var i PolicyCategory
		if err := rows.Scan(&i.ID, &i.Title, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyCategoryById = `-- name: GetPolicyCategoryById :one
SELECT id, title, sort_order FROM policy_category WHERE id = ?
`

func (q *Queries) GetPolicyCategoryById(ctx context.Context, id int32) (PolicyCategory, error) {
	row := q.db.QueryRowContext(ctx, getPolicyCategoryById, id)
	var i PolicyCategory
	err := row.Scan(&i.ID, &i.Title, &i.SortOrder)
	return i, err
}

const updatePolicyCategory = `-- name: UpdatePolicyCategory :execresult
UPDATE policy_category
SET title = ?, sort_order = ?
WHERE id = ?
`

type UpdatePolicyCategoryParams struct {
	Title     string
	SortOrder int32
	ID        int32
}

func (q *Queries) UpdatePolicyCategory(ctx context.Context, arg UpdatePolicyCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePolicyCategory, arg.Title, arg.SortOrder, arg.ID)
}
