// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"
)

const createFacilityRole = `-- name: CreateFacilityRole :exec
INSERT INTO role_facility (cid, role, facility, created_at, created_by)
VALUES(?, ?, ?, ?, ?)
`

type CreateFacilityRoleParams struct {
	Cid       int32
	Role      string
	Facility  string
	CreatedAt int64
	CreatedBy int32
}

func (q *Queries) CreateFacilityRole(ctx context.Context, arg CreateFacilityRoleParams) error {
	_, err := q.db.ExecContext(ctx, createFacilityRole,
		arg.Cid,
		arg.Role,
		arg.Facility,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const createGlobalRole = `-- name: CreateGlobalRole :exec
INSERT INTO role_global (cid, role, created_at, created_by)
VALUES(?, ?, ?, ?)
`

type CreateGlobalRoleParams struct {
	Cid       int32
	Role      string
	CreatedAt int64
	CreatedBy int32
}

func (q *Queries) CreateGlobalRole(ctx context.Context, arg CreateGlobalRoleParams) error {
	_, err := q.db.ExecContext(ctx, createGlobalRole,
		arg.Cid,
		arg.Role,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const deleteUserFacilityRoles = `-- name: DeleteUserFacilityRoles :exec
DELETE FROM role_facility WHERE cid = ?
`

func (q *Queries) DeleteUserFacilityRoles(ctx context.Context, cid int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserFacilityRoles, cid)
	return err
}

const deleteUserGlobalRoles = `-- name: DeleteUserGlobalRoles :exec
DELETE FROM role_global WHERE cid = ?
`

func (q *Queries) DeleteUserGlobalRoles(ctx context.Context, cid int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserGlobalRoles, cid)
	return err
}

const fetchFacilityRolesByCID = `-- name: FetchFacilityRolesByCID :many
SELECT id, cid, role, facility, created_at, created_by
FROM role_facility
WHERE cid = ?
`

func (q *Queries) FetchFacilityRolesByCID(ctx context.Context, cid int32) ([]RoleFacility, error) {
	rows, err := q.db.QueryContext(ctx, fetchFacilityRolesByCID, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleFacility
	for rows.Next() {
		var i RoleFacility
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Role,
			&i.Facility,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchGlobalRolesByCID = `-- name: FetchGlobalRolesByCID :many
SELECT id, cid, role, created_at, created_by
FROM role_global
WHERE cid = ?
`

func (q *Queries) FetchGlobalRolesByCID(ctx context.Context, cid int32) ([]RoleGlobal, error) {
	rows, err := q.db.QueryContext(ctx, fetchGlobalRolesByCID, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleGlobal
	for rows.Next() {
		var i RoleGlobal
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Role,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
