// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: solo_cert.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSoloCert = `-- name: CreateSoloCert :execresult
INSERT INTO solo_cert (cid, facility, position, expires, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSoloCertParams struct {
	Cid       int64
	Facility  string
	Position  string
	Expires   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateSoloCert(ctx context.Context, arg CreateSoloCertParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSoloCert,
		arg.Cid,
		arg.Facility,
		arg.Position,
		arg.Expires,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteSoloCert = `-- name: DeleteSoloCert :exec
DELETE FROM solo_cert WHERE id = ?
`

func (q *Queries) DeleteSoloCert(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSoloCert, id)
	return err
}

const getActiveSoloCerts = `-- name: GetActiveSoloCerts :many
SELECT id, cid, facility, position, expires, created_at, updated_at FROM solo_cert WHERE expires >= CURDATE() ORDER BY expires ASC
`

func (q *Queries) GetActiveSoloCerts(ctx context.Context) ([]SoloCert, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSoloCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoloCert
	for rows.Next() {
		var i SoloCert
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Facility,
			&i.Position,
			&i.Expires,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSoloCertById = `-- name: GetSoloCertById :one
SELECT id, cid, facility, position, expires, created_at, updated_at FROM solo_cert WHERE id = ?
`

func (q *Queries) GetSoloCertById(ctx context.Context, id int64) (SoloCert, error) {
	row := q.db.QueryRowContext(ctx, getSoloCertById, id)
	var i SoloCert
	err := row.Scan(
		&i.ID,
		&i.Cid,
		&i.Facility,
		&i.Position,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSoloCert = `-- name: UpdateSoloCert :exec
UPDATE solo_cert
SET facility = ?, position = ?, expires = ?, updated_at = ?
WHERE id = ?
`

type UpdateSoloCertParams struct {
	Facility  string
	Position  string
	Expires   time.Time
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSoloCert(ctx context.Context, arg UpdateSoloCertParams) error {
	_, err := q.db.ExecContext(ctx, updateSoloCert,
		arg.Facility,
		arg.Position,
		arg.Expires,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
