// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTransferHistoryRecord = `-- name: CreateTransferHistoryRecord :execresult
INSERT INTO transfer_history (cid, from_facility, to_facility, reason, requested_at, completed_at, approver_cid)
VALUES (?, ?, ?, ?, ?, NOW(), ?)
`

type CreateTransferHistoryRecordParams struct {
	Cid          int64
	FromFacility string
	ToFacility   string
	Reason       string
	RequestedAt  time.Time
	ApproverCid  sql.NullInt64
}

func (q *Queries) CreateTransferHistoryRecord(ctx context.Context, arg CreateTransferHistoryRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransferHistoryRecord,
		arg.Cid,
		arg.FromFacility,
		arg.ToFacility,
		arg.Reason,
		arg.RequestedAt,
		arg.ApproverCid,
	)
}

const createTransferRequest = `-- name: CreateTransferRequest :execresult
INSERT INTO transfer_request (cid, from_facility, to_facility, reason, created_at, status)
VALUES (?, ?, ?, ?, NOW(), 'pending')
`

type CreateTransferRequestParams struct {
	Cid          int64
	FromFacility string
	ToFacility   string
	Reason       string
}

func (q *Queries) CreateTransferRequest(ctx context.Context, arg CreateTransferRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransferRequest,
		arg.Cid,
		arg.FromFacility,
		arg.ToFacility,
		arg.Reason,
	)
}

const deleteTransferRequest = `-- name: DeleteTransferRequest :exec
DELETE FROM transfer_request WHERE id = ?
`

func (q *Queries) DeleteTransferRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransferRequest, id)
	return err
}

const getCountPendingTransferRequestsForCID = `-- name: GetCountPendingTransferRequestsForCID :one
SELECT count(*)
FROM transfer_request
WHERE cid = ? AND status = 'pending'
`

func (q *Queries) GetCountPendingTransferRequestsForCID(ctx context.Context, cid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountPendingTransferRequestsForCID, cid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingTransferRequestsForFacility = `-- name: GetPendingTransferRequestsForFacility :many
SELECT id, cid, from_facility, to_facility, reason, created_at, status
FROM transfer_request
WHERE to_facility = ? AND status = 'pending'
`

func (q *Queries) GetPendingTransferRequestsForFacility(ctx context.Context, toFacility string) ([]TransferRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTransferRequestsForFacility, toFacility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferRequest
	for rows.Next() {
		var i TransferRequest
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.FromFacility,
			&i.ToFacility,
			&i.Reason,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferHistoryForCID = `-- name: GetTransferHistoryForCID :many
SELECT id, cid, from_facility, to_facility, reason, requested_at, completed_at, approver_cid
FROM transfer_history
WHERE cid = ?
`

func (q *Queries) GetTransferHistoryForCID(ctx context.Context, cid int64) ([]TransferHistory, error) {
	rows, err := q.db.QueryContext(ctx, getTransferHistoryForCID, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferHistory
	for rows.Next() {
		var i TransferHistory
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.FromFacility,
			&i.ToFacility,
			&i.Reason,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.ApproverCid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferRequestById = `-- name: GetTransferRequestById :one
SELECT id, cid, from_facility, to_facility, reason, created_at, status
FROM transfer_request
WHERE id = ?
`

func (q *Queries) GetTransferRequestById(ctx context.Context, id int64) (TransferRequest, error) {
	row := q.db.QueryRowContext(ctx, getTransferRequestById, id)
	var i TransferRequest
	err := row.Scan(
		&i.ID,
		&i.Cid,
		&i.FromFacility,
		&i.ToFacility,
		&i.Reason,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getTransferRequestsForCID = `-- name: GetTransferRequestsForCID :many
SELECT id, cid, from_facility, to_facility, reason, created_at, status
FROM transfer_request
WHERE cid = ?
`

func (q *Queries) GetTransferRequestsForCID(ctx context.Context, cid int64) ([]TransferRequest, error) {
	rows, err := q.db.QueryContext(ctx, getTransferRequestsForCID, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferRequest
	for rows.Next() {
		var i TransferRequest
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.FromFacility,
			&i.ToFacility,
			&i.Reason,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferRequestStatus = `-- name: UpdateTransferRequestStatus :exec
UPDATE transfer_request SET status = ? WHERE id = ?
`

type UpdateTransferRequestStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateTransferRequestStatus(ctx context.Context, arg UpdateTransferRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferRequestStatus, arg.Status, arg.ID)
	return err
}
