// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getCombinedUserByCID = `-- name: GetCombinedUserByCID :one
SELECT vu.cid
     , vu.name_first
     , vu.name_last
     , vu.email
     , vu.rating
     , vu.pilotrating
     , vu.militaryrating
     , vu.region_id
     , vu.division_id
     , vu.subdivision_id
     , vu.latest_rating_change
     , vu.last_sync
     , u.display_name
     , u.controller_rating
     , u.instructor_rating
     , u.facility
     , (SELECT GROUP_CONCAT(facility SEPARATOR ',') from user_visit uv where uv.cid = u.cid) as visiting_facilities
     , u.discord_id
     , u.last_promotion_time
     , u.last_transfer_time
from vatsim_user vu
         left join user u on vu.cid = u.cid
where vu.cid = ?
`

type GetCombinedUserByCIDRow struct {
	Cid                int64
	NameFirst          string
	NameLast           string
	Email              string
	Rating             int32
	Pilotrating        int32
	Militaryrating     int32
	RegionID           string
	DivisionID         string
	SubdivisionID      sql.NullString
	LatestRatingChange sql.NullTime
	LastSync           time.Time
	DisplayName        sql.NullString
	ControllerRating   sql.NullInt32
	InstructorRating   sql.NullInt32
	Facility           sql.NullString
	VisitingFacilities sql.NullString
	DiscordID          sql.NullString
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
}

func (q *Queries) GetCombinedUserByCID(ctx context.Context, cid int64) (GetCombinedUserByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCombinedUserByCID, cid)
	var i GetCombinedUserByCIDRow
	err := row.Scan(
		&i.Cid,
		&i.NameFirst,
		&i.NameLast,
		&i.Email,
		&i.Rating,
		&i.Pilotrating,
		&i.Militaryrating,
		&i.RegionID,
		&i.DivisionID,
		&i.SubdivisionID,
		&i.LatestRatingChange,
		&i.LastSync,
		&i.DisplayName,
		&i.ControllerRating,
		&i.InstructorRating,
		&i.Facility,
		&i.VisitingFacilities,
		&i.DiscordID,
		&i.LastPromotionTime,
		&i.LastTransferTime,
	)
	return i, err
}

const getUserByCID = `-- name: GetUserByCID :one
SELECT u.cid, u.display_name, u.controller_rating, u.instructor_rating, u.facility, u.discord_id, u.last_promotion_time, u.last_transfer_time, u.last_competency_date,
       (SELECT GROUP_CONCAT(facility SEPARATOR ',') from user_visit uv where uv.cid = user.cid) as visiting_facilities
FROM user u
WHERE u.cid = ?
`

type GetUserByCIDRow struct {
	Cid                int64
	DisplayName        sql.NullString
	ControllerRating   sql.NullInt32
	InstructorRating   sql.NullInt32
	Facility           string
	DiscordID          sql.NullString
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
	LastCompetencyDate sql.NullTime
	VisitingFacilities sql.NullString
}

func (q *Queries) GetUserByCID(ctx context.Context, cid int64) (GetUserByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByCID, cid)
	var i GetUserByCIDRow
	err := row.Scan(
		&i.Cid,
		&i.DisplayName,
		&i.ControllerRating,
		&i.InstructorRating,
		&i.Facility,
		&i.DiscordID,
		&i.LastPromotionTime,
		&i.LastTransferTime,
		&i.LastCompetencyDate,
		&i.VisitingFacilities,
	)
	return i, err
}

const upsertUserForMigration = `-- name: UpsertUserForMigration :exec
INSERT INTO user (cid, controller_rating, instructor_rating, facility, discord_id, last_promotion_time,
                  last_transfer_time, last_competency_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE controller_rating    = VALUES(controller_rating),
                        instructor_rating    = VALUES(instructor_rating),
                        facility             = VALUES(facility),
                        discord_id           = VALUES(discord_id),
                        last_promotion_time  = VALUES(last_promotion_time),
                        last_transfer_time   = VALUES(last_transfer_time),
                        last_competency_date = VALUES(last_competency_date)
`

type UpsertUserForMigrationParams struct {
	Cid                int64
	ControllerRating   sql.NullInt32
	InstructorRating   sql.NullInt32
	Facility           string
	DiscordID          sql.NullString
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
	LastCompetencyDate sql.NullTime
}

func (q *Queries) UpsertUserForMigration(ctx context.Context, arg UpsertUserForMigrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserForMigration,
		arg.Cid,
		arg.ControllerRating,
		arg.InstructorRating,
		arg.Facility,
		arg.DiscordID,
		arg.LastPromotionTime,
		arg.LastTransferTime,
		arg.LastCompetencyDate,
	)
	return err
}
