// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const getCombinedUser = `-- name: GetCombinedUser :many
SELECT vu.cid
     , vu.name_first
     , vu.name_last
     , vu.email
     , vu.rating
     , vu.pilotrating
     , vu.militaryrating
     , vu.region_id
     , vu.division_id
     , vu.subdivision_id
     , vu.latest_rating_change
     , vu.last_sync
     , u.display_name
     , u.controller_rating
     , u.instructor_rating
     , u.facility
     , (SELECT GROUP_CONCAT(facility SEPARATOR ',') from user_visit uv where uv.cid = u.cid) as visiting_facilities
     , u.discord_id
     , u.last_promotion_time
     , u.last_transfer_time
     , u.last_visit_time
     , u.last_competency_date
from vatsim_user vu
         join user u on vu.cid = u.cid
where (? is null OR vu.cid = ?)
AND (? IS NULL OR vu.cid IN (/*SLICE:cids*/?))
AND (? is null or u.facility = ?)
AND (? is null or u.cid IN (select cid from user_visit uv where uv.facility = ?))
`

type GetCombinedUserParams struct {
	Cid           sql.NullInt64
	HasCidsSlice  interface{}
	Cids          []int64
	HomeFacility  sql.NullString
	VisitFacility sql.NullString
}

type GetCombinedUserRow struct {
	Cid                int64
	NameFirst          string
	NameLast           string
	Email              string
	Rating             int32
	Pilotrating        int32
	Militaryrating     int32
	RegionID           string
	DivisionID         string
	SubdivisionID      sql.NullString
	LatestRatingChange sql.NullTime
	LastSync           sql.NullTime
	DisplayName        string
	ControllerRating   int32
	InstructorRating   int32
	Facility           string
	VisitingFacilities sql.NullString
	DiscordID          string
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
	LastVisitTime      sql.NullTime
	LastCompetencyDate sql.NullTime
}

func (q *Queries) GetCombinedUser(ctx context.Context, arg GetCombinedUserParams) ([]GetCombinedUserRow, error) {
	query := getCombinedUser
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Cid)
	queryParams = append(queryParams, arg.Cid)
	queryParams = append(queryParams, arg.HasCidsSlice)
	if len(arg.Cids) > 0 {
		for _, v := range arg.Cids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:cids*/?", strings.Repeat(",?", len(arg.Cids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:cids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.HomeFacility)
	queryParams = append(queryParams, arg.HomeFacility)
	queryParams = append(queryParams, arg.VisitFacility)
	queryParams = append(queryParams, arg.VisitFacility)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCombinedUserRow
	for rows.Next() {
		var i GetCombinedUserRow
		if err := rows.Scan(
			&i.Cid,
			&i.NameFirst,
			&i.NameLast,
			&i.Email,
			&i.Rating,
			&i.Pilotrating,
			&i.Militaryrating,
			&i.RegionID,
			&i.DivisionID,
			&i.SubdivisionID,
			&i.LatestRatingChange,
			&i.LastSync,
			&i.DisplayName,
			&i.ControllerRating,
			&i.InstructorRating,
			&i.Facility,
			&i.VisitingFacilities,
			&i.DiscordID,
			&i.LastPromotionTime,
			&i.LastTransferTime,
			&i.LastVisitTime,
			&i.LastCompetencyDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByCID = `-- name: GetUserByCID :one
SELECT u.cid, u.facility, u.last_promotion_time, u.last_transfer_time, u.last_competency_date, u.display_name, u.controller_rating, u.instructor_rating, u.discord_id, u.last_visit_time,
       (SELECT GROUP_CONCAT(facility SEPARATOR ',') from user_visit uv where uv.cid = u.cid) as visiting_facilities
FROM user u
WHERE u.cid = ?
`

type GetUserByCIDRow struct {
	Cid                int64
	Facility           string
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
	LastCompetencyDate sql.NullTime
	DisplayName        string
	ControllerRating   int32
	InstructorRating   int32
	DiscordID          string
	LastVisitTime      sql.NullTime
	VisitingFacilities sql.NullString
}

func (q *Queries) GetUserByCID(ctx context.Context, cid int64) (GetUserByCIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByCID, cid)
	var i GetUserByCIDRow
	err := row.Scan(
		&i.Cid,
		&i.Facility,
		&i.LastPromotionTime,
		&i.LastTransferTime,
		&i.LastCompetencyDate,
		&i.DisplayName,
		&i.ControllerRating,
		&i.InstructorRating,
		&i.DiscordID,
		&i.LastVisitTime,
		&i.VisitingFacilities,
	)
	return i, err
}

const getUserRatingHourCheckCids = `-- name: GetUserRatingHourCheckCids :many
SELECT u.cid
FROM user u
JOIN vatsim_user vu on u.cid = vu.cid
LEFT JOIN user_rating_hours h ON u.cid = h.cid AND h.rating = least(u.controller_rating, 5)
WHERE (h.hours IS NULL or h.hours < ?)
AND u.controller_rating > 1
AND (u.controller_rating >= 4 OR (vu.region_id = 'AMAS' AND vu.division_id = 'USA'))
`

func (q *Queries) GetUserRatingHourCheckCids(ctx context.Context, hours int32) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatingHourCheckCids, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var cid int64
		if err := rows.Scan(&cid); err != nil {
			return nil, err
		}
		items = append(items, cid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRatingHours = `-- name: GetUserRatingHours :one
SELECT cid, rating, hours, last_check_time
FROM user_rating_hours
WHERE cid = ? AND rating = ?
`

type GetUserRatingHoursParams struct {
	Cid    int64
	Rating int32
}

func (q *Queries) GetUserRatingHours(ctx context.Context, arg GetUserRatingHoursParams) (UserRatingHour, error) {
	row := q.db.QueryRowContext(ctx, getUserRatingHours, arg.Cid, arg.Rating)
	var i UserRatingHour
	err := row.Scan(
		&i.Cid,
		&i.Rating,
		&i.Hours,
		&i.LastCheckTime,
	)
	return i, err
}

const insertUserFromVatsimSync = `-- name: InsertUserFromVatsimSync :exec
INSERT IGNORE INTO user (cid, display_name, controller_rating, instructor_rating, facility)
VALUES (?, ?, 0, 0, ?)
`

type InsertUserFromVatsimSyncParams struct {
	Cid         int64
	DisplayName string
	Facility    string
}

func (q *Queries) InsertUserFromVatsimSync(ctx context.Context, arg InsertUserFromVatsimSyncParams) error {
	_, err := q.db.ExecContext(ctx, insertUserFromVatsimSync, arg.Cid, arg.DisplayName, arg.Facility)
	return err
}

const storeUserRatingHours = `-- name: StoreUserRatingHours :exec
INSERT INTO user_rating_hours (cid, rating, hours, last_check_time) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE hours = VALUES(hours), last_check_time = VALUES(last_check_time)
`

type StoreUserRatingHoursParams struct {
	Cid           int64
	Rating        int32
	Hours         int32
	LastCheckTime time.Time
}

func (q *Queries) StoreUserRatingHours(ctx context.Context, arg StoreUserRatingHoursParams) error {
	_, err := q.db.ExecContext(ctx, storeUserRatingHours,
		arg.Cid,
		arg.Rating,
		arg.Hours,
		arg.LastCheckTime,
	)
	return err
}

const updateUserForTransfer = `-- name: UpdateUserForTransfer :exec
UPDATE user SET facility = ?, last_transfer_time = ? WHERE cid = ?
`

type UpdateUserForTransferParams struct {
	Facility         string
	LastTransferTime sql.NullTime
	Cid              int64
}

func (q *Queries) UpdateUserForTransfer(ctx context.Context, arg UpdateUserForTransferParams) error {
	_, err := q.db.ExecContext(ctx, updateUserForTransfer, arg.Facility, arg.LastTransferTime, arg.Cid)
	return err
}

const upsertUserForMigration = `-- name: UpsertUserForMigration :exec
INSERT INTO user (cid, controller_rating, instructor_rating, facility, discord_id, last_promotion_time,
                  last_transfer_time, last_competency_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE controller_rating    = VALUES(controller_rating),
                        instructor_rating    = VALUES(instructor_rating),
                        facility             = VALUES(facility),
                        discord_id           = VALUES(discord_id),
                        last_promotion_time  = VALUES(last_promotion_time),
                        last_transfer_time   = VALUES(last_transfer_time),
                        last_competency_date = VALUES(last_competency_date)
`

type UpsertUserForMigrationParams struct {
	Cid                int64
	ControllerRating   int32
	InstructorRating   int32
	Facility           string
	DiscordID          string
	LastPromotionTime  sql.NullTime
	LastTransferTime   sql.NullTime
	LastCompetencyDate sql.NullTime
}

func (q *Queries) UpsertUserForMigration(ctx context.Context, arg UpsertUserForMigrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserForMigration,
		arg.Cid,
		arg.ControllerRating,
		arg.InstructorRating,
		arg.Facility,
		arg.DiscordID,
		arg.LastPromotionTime,
		arg.LastTransferTime,
		arg.LastCompetencyDate,
	)
	return err
}
