// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v3_api_key.sql

package db

import (
	"context"
	"database/sql"
)

const getV3ApiKeysByFacility = `-- name: GetV3ApiKeysByFacility :many
SELECT id, code, testing, facility, notes, created_at, updated_at, deleted_at FROM v3_api_key
WHERE facility = ? AND deleted_at IS NULL
ORDER BY testing ASC, id ASC
`

func (q *Queries) GetV3ApiKeysByFacility(ctx context.Context, facility sql.NullString) ([]V3ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getV3ApiKeysByFacility, facility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []V3ApiKey
	for rows.Next() {
		var i V3ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Testing,
			&i.Facility,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
