// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vatsim_user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getVatsimUserByCid = `-- name: GetVatsimUserByCid :one
SELECT cid, name_first, name_last, email, rating, pilotrating, militaryrating, suspend_date, registration_date, region_id, division_id, subdivision_id, latest_rating_change, last_sync
FROM vatsim_user
WHERE cid = ?
`

func (q *Queries) GetVatsimUserByCid(ctx context.Context, cid int64) (VatsimUser, error) {
	row := q.db.QueryRowContext(ctx, getVatsimUserByCid, cid)
	var i VatsimUser
	err := row.Scan(
		&i.Cid,
		&i.NameFirst,
		&i.NameLast,
		&i.Email,
		&i.Rating,
		&i.Pilotrating,
		&i.Militaryrating,
		&i.SuspendDate,
		&i.RegistrationDate,
		&i.RegionID,
		&i.DivisionID,
		&i.SubdivisionID,
		&i.LatestRatingChange,
		&i.LastSync,
	)
	return i, err
}

const upsertVatsimUser = `-- name: UpsertVatsimUser :exec
INSERT INTO vatsim_user (cid, name_first, name_last, email, rating, pilotrating, militaryrating,
                         suspend_date, registration_date, region_id, division_id, subdivision_id, latest_rating_change,
                         last_sync)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE name_first           = VALUES(name_first),
                        name_last            = VALUES(name_last),
                        email                = VALUES(email),
                        rating               = VALUES(rating),
                        pilotrating          = VALUES(pilotrating),
                        militaryrating       = VALUES(militaryrating),
                        suspend_date         = VALUES(suspend_date),
                        registration_date    = VALUES(registration_date),
                        region_id            = VALUES(region_id),
                        division_id          = VALUES(division_id),
                        subdivision_id       = VALUES(subdivision_id),
                        latest_rating_change = VALUES(latest_rating_change),
                        last_sync            = VALUES(last_sync)
`

type UpsertVatsimUserParams struct {
	Cid                int64
	NameFirst          string
	NameLast           string
	Email              string
	Rating             int32
	Pilotrating        int32
	Militaryrating     int32
	SuspendDate        sql.NullTime
	RegistrationDate   sql.NullTime
	RegionID           string
	DivisionID         string
	SubdivisionID      sql.NullString
	LatestRatingChange sql.NullTime
	LastSync           time.Time
}

func (q *Queries) UpsertVatsimUser(ctx context.Context, arg UpsertVatsimUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertVatsimUser,
		arg.Cid,
		arg.NameFirst,
		arg.NameLast,
		arg.Email,
		arg.Rating,
		arg.Pilotrating,
		arg.Militaryrating,
		arg.SuspendDate,
		arg.RegistrationDate,
		arg.RegionID,
		arg.DivisionID,
		arg.SubdivisionID,
		arg.LatestRatingChange,
		arg.LastSync,
	)
	return err
}
